### ISSUE TITLE
RDFReactor Code Generator build fails with failed unit test

### ISSUE THREAD

**Issue by l337r007** [semweb4j/semweb4j#16]
```
testReac15(org.ontoware.rdfreactor.generator.TestReportedBugs)  Time elapsed: 0.092 sec  <<< ERROR!
java.util.ConcurrentModificationException: null
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901)
	at java.util.ArrayList$Itr.next(ArrayList.java:851)
	at org.apache.velocity.runtime.directive.Foreach.render(Foreach.java:431)
	at org.apache.velocity.runtime.parser.node.ASTDirective.render(ASTDirective.java:170)
	at org.apache.velocity.runtime.parser.node.SimpleNode.render(SimpleNode.java:318)
	at org.apache.velocity.Template.merge(Template.java:254)
	at org.ontoware.rdfreactor.generator.SourceCodeWriter.writeClass(SourceCodeWriter.java:199)
	at org.ontoware.rdfreactor.generator.SourceCodeWriter.writePackage(SourceCodeWriter.java:230)
	at org.ontoware.rdfreactor.generator.SourceCodeWriter.writeModel(SourceCodeWriter.java:182)
	at org.ontoware.rdfreactor.generator.SourceCodeWriter.write(SourceCodeWriter.java:99)
	at org.ontoware.rdfreactor.generator.CodeGenerator.generate(CodeGenerator.java:175)
	at org.ontoware.rdfreactor.generator.CodeGenerator.generate(CodeGenerator.java:79)
	at org.ontoware.rdfreactor.generator.CodeGenerator.generate(CodeGenerator.java:109)
	at org.ontoware.rdfreactor.generator.TestReportedBugs.testReac15(TestReportedBugs.java:33)
```
Environment:
```
Apache Maven 3.3.1 (cab6659f9874fa96462afef40fcf6bc033d58c1c; 2015-03-13T21:10:27+01:00)
Maven home: /usr/local/Cellar/maven/3.3.1/libexec
Java version: 1.8.0_31, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.8.0_31.jdk/Contents/Home/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.10.5", arch: "x86_64", family: "mac"
```

**Comment by stuehmer** [comment]
Still no progress here, any hints welcome.

After this is fixed a new version including pull request #15 can be made.

**Comment by earcam** [comment]
Hi,

For a workaround, look at [this diff](https://github.com/earcam/semweb4j/commit/e21d29a192c5d66ec3752009fd0f9ce829ec3828)

Basically just change the instantiation of `JClass.properties` to `new CopyOnWriteArrayList` (the velocity update is irrelevant, but likely worthwhile).

The `testReac15` then test passes and I'm able to use the maven plugin etc.
